# This is a basic workflow to help you get started with Actions

name: web-front CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["web-front"]
  pull_request:
    branches: ["web-front"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/front

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: chmod +x web/front/scripts/check.sh
      - run: |
          cd ../..
          web/front/scripts/check.sh
      - run: npm install
      # - run: npm run dev
      # - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
